### ISSUE TITLE
"goldwarden setup systemd" as root crashes

### ISSUE THREAD

**Issue by Mte90** [quexten/goldwarden#101]
So I was following https://github.com/quexten/goldwarden/wiki/Getting-Started that doesn't explain the permission for the commands on Linux.
So for polkit no issues but for systemd:
```
Failed to enable unit: Process org.freedesktop.systemd1 exited with status 1
failed enabling systemd service
panic: exit status 1

goroutine 1 [running]:
github.com/quexten/goldwarden/cmd.setupSystemd()
        /home/runner/work/goldwarden/goldwarden/cmd/setup_linux.go:117 +0x3dd
github.com/quexten/goldwarden/cmd.glob..func17(0xc96360?, {0x92d806?, 0x0?, 0x0?})
        /home/runner/work/goldwarden/goldwarden/cmd/setup_linux.go:128 +0x17
github.com/spf13/cobra.(*Command).execute(0xc96360, {0xd06198, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0xc95ac0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/quexten/goldwarden/cmd.Execute({0x0, 0x0, {0x0, 0x0}, 0x0, {0xc000034ab0, 0x28}, 0x0, 0x0, {0x0, ...}, ...})
        /home/runner/work/goldwarden/goldwarden/cmd/root.go:35 +0x1fb
main.main()
        /home/runner/work/goldwarden/goldwarden/main.go:83 +0x965
```

I think that in that case for root user there should be an alert to run it on the user itself.

**Comment by quexten** [comment]
f224276749f53e686f5bf5c22e69ba19cc8be7d2

Added detection and notification in setup now.
