### ISSUE TITLE
Goldwarden daemonize not working (listen error listen unix ~/.goldwarden.sock: bind: no such file or directory)

### ISSUE THREAD

**Issue by zany130** [quexten/goldwarden#125]
Noticed goldwarden was no longer working so I tried manually running `goldwarden daemonize` and I get 
```
SSH Agent socket path is empty, overwriting with default path.
[INF] [21:13] [Goldwarden > Keyring] >>> Creating new memguard keyring
listen error listen unix ~/.goldwarden.sock: bind: no such file or directory
panic: listen unix ~/.goldwarden.sock: bind: no such file or directory

goroutine 1 [running]:
github.com/quexten/goldwarden/cmd.init.func15(0xc0000d8f00?, {0x5871f0329474?, 0x4?, 0x5871f0329354?})
	github.com/quexten/goldwarden/cmd/daemonize.go:70 +0x425
github.com/spf13/cobra.(*Command).execute(0x5871f07aaf80, {0x5871f08492c0, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x5871f07ab820)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/quexten/goldwarden/cmd.Execute({{0x0, 0x0}, 0x0, {0xc00002ee10, 0x30}, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...})
	github.com/quexten/goldwarden/cmd/root.go:29 +0xe6
main.main()
	github.com/quexten/goldwarden/main.go:52 +0x5f8
	```
	cat the file shows the it exists but is empty 
	
	```
	cat ~/.goldwarden.sock
File: /home/zany130/.goldwarden.sock   <EMPTY>
```
```
System:
  Host: Garuda-Linux Kernel: 6.7.6-1-cachyos arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 5.27.10 Distro: Garuda Linux
  ```
  installed from the aur version: 0.2.13-1

**Comment by zany130** [comment]
tried reinstalling goldwarden today ( i also deleted the user systems service and the config folder as well as all the `.goldwarden` sockets in my home )to see if this would fix it and no luck

interestingly when I go to setup polkit I get 

```
goldwarden setup polkit
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/chown root:root /usr/share/po ... actions/com.quexten.goldwarden.policy' as the super user
Authenticating as: Andres David Ortiz (zany130)
Password:
==== AUTHENTICATION FAILED ====
panic: exit status 127

goroutine 1 [running]:
github.com/quexten/goldwarden/cmd.setupPolkit()
	github.com/quexten/goldwarden/cmd/setup_linux.go:54 +0x466
github.com/quexten/goldwarden/cmd.init.func24(0xc0001e3200?, {0x5f5c88ac6474?, 0x4?, 0x5f5c88ac6354?})
	github.com/quexten/goldwarden/cmd/setup_linux.go:80 +0xf
github.com/spf13/cobra.(*Command).execute(0x5f5c88f49c40, {0x5f5c88fe62c0, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x5f5c88f48820)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/quexten/goldwarden/cmd.Execute({{0x0, 0x0}, 0x0, {0xc0001aab70, 0x30}, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...})
	github.com/quexten/goldwarden/cmd/root.go:29 +0xe6
main.main()
	github.com/quexten/goldwarden/main.go:52 +0x5f8
	```
	damonize still causes the following error
	
	```
	goldwarden daemonize
SSH Agent socket path is empty, overwriting with default path.
[INF] [15:23] [Goldwarden > Keyring] >>> Creating new memguard keyring
[WRN] [15:23] [Goldwarden > Agent] >>> Config is not locked. SET A PIN!!
listen error listen unix ~/.goldwarden.sock: bind: no such file or directory
panic: listen unix ~/.goldwarden.sock: bind: no such file or directory

goroutine 1 [running]:
github.com/quexten/goldwarden/cmd.init.func15(0xc000168f00?, {0x62ba3783d474?, 0x4?, 0x62ba3783d354?})
	github.com/quexten/goldwarden/cmd/daemonize.go:70 +0x425
github.com/spf13/cobra.(*Command).execute(0x62ba37cbef80, {0x62ba37d5d2c0, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x62ba37cbf820)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/quexten/goldwarden/cmd.Execute({{0x0, 0x0}, 0x0, {0xc000132b70, 0x30}, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...})
	github.com/quexten/goldwarden/cmd/root.go:29 +0xe6
main.main()
	github.com/quexten/goldwarden/main.go:52 +0x5f8
	```

**Comment by zany130** [comment]
It seems it might of been user error that got me into the original situation. I can confirm now though that everything is working as of `0.2.16` including polkit and ssh. 
Note I do still get the same error but I'll post more int the polkit issue to avoid cluttering this issue anymore lol.
