### ISSUE TITLE
Bad password no matter what I do

### ISSUE THREAD

**Issue by Fxsch** [quexten/goldwarden#147]
I changed my email recently, so I'm trying to log in again but it just doesn't work no matter what I do. I set the PIN to my Bitwarden password (I'm not sure but I think the PIN can be different), I tried entering just my email in the login and it first told me `Bad password`, without me having entered my password, then it prompted me to enter my password, I did and it still told me `Bad password`. This was also after the third reinstall (I also deleted the app data) and it was the only time it actually asked me for my password, even though I tried logging in multiple times. I also tried entering the Client ID and Client Secret but it still told me `Bad password` (I tried entering the ID with and without the `user.`). This is a great and very useful application and I'm very thankful for everyone involved in maintaining it. I hope it wasn't too obvious that I'm pretty pissed off right now but it kinda sucks that it just won't work the one time I actually need it.

**OS:** Fedora Linux 39 (Kernel 6.7.9)
**Installation method:** Flatpak

**Comment by quexten** [comment]
>  This is a great and very useful application and I'm very thankful for everyone involved in maintaining it. I hope it wasn't too obvious that I'm pretty pissed off right now but it kinda sucks that it just won't work the one time I actually need it.

No worries. I didn't even get that impression from your post.

Let's break this down.
First, for the pin, this can be different from your bitwarden password.
>  I tried entering just my email in the login and it first told me Bad password, without me having entered my password, then it prompted me to enter my password, I did and it still told me Bad password. 

This sounds like internal state is somehow corrupted. As you mentioned you deleted the app data, but can you still try rm -rf'ing ~/.var/app/com.quexten.Goldwarden/
, then running flatpak kill com.quexten.Goldwarden 
and then restarting Goldwarden via flatpak run com.quexten.Goldwarden ?

Starting it in this way ensures you have a clean state, and also should output logs in the console you run the flatpak run command from. Then, post the log here, but make sure to look for sensitive information, and redact it. Usually, no sensitive information should be logged, but i'm noting this just in case it's accidentally logged.

>  I also tried entering the Client ID and Client Secret but it still told me Bad password

Is this a self hosted installation or official vault.bitwarden.com?

**Comment by ImJustToNy** [comment]
I'm having the same problem. I tried removing ~/.var/app/com.quexten.Goldwarden/ and rerunning app. Still no luck.
I use vault.bitwarden.eu. Here are my logs:
```
❯ flatpak run com.quexten.Goldwarden
starting goldwarden daemon /app/bin/goldwarden
[INF] [00:24] [Goldwarden > Keyring] >>> Creating new memguard keyring
[WRN] [00:24] [Goldwarden > Agent] >>> Could not read config: open /home/tony/.var/app/com.quexten.Goldwarden/config/goldwarden.json: no such file or directory
[WRN] [00:24] [Goldwarden > Agent] >>> Config is not locked. SET A PIN!!
[INF] [00:24] [Goldwarden > Agent] >>> Agent listening on /home/tony/.var/app/com.quexten.Goldwarden/data/goldwarden.sock...
[INF] [00:24] [Goldwarden > SSH] >>> SSH Agent listening on /home/tony/.var/app/com.quexten.Goldwarden/data/ssh-auth-sock
[WRN] [00:24] [Goldwarden > Agent] >>> Could not monitor idle: org.freedesktop.DBus.Error.ServiceUnknown
listening for pinentry /app/bin/goldwarden
Enabling autostart...
[INF] [00:24] [Goldwarden > Agent] >>> Received pinentry registration request
[INF] [00:24] [Goldwarden > Agent] >>> Pinentry registration success: true
autostart enabled..!?
(':1.101', '/org/freedesktop/portal/desktop/request/1_1433/com/quexten/Goldwarden/16256414', 'org.freedesktop.portal.Request', 'Response', GLib.Variant('(ua{sv})', (0, {'background': <true>, 'autostart': <true>})), None)
/app/bin/src/gui/settings.py:84: DeprecationWarning: Gtk.Widget.get_style_context is deprecated
  self.autotype_button.get_style_context().add_class("suggested-action")
/app/bin/src/gui/settings.py:84: DeprecationWarning: Gtk.StyleContext.add_class is deprecated
  self.autotype_button.get_style_context().add_class("suggested-action")
/app/bin/src/gui/settings.py:44: DeprecationWarning: Adw.ActionRow.set_icon_name is deprecated
  row.set_icon_name(icon)
[INF] [00:25] [Goldwarden > Pinentry] >>> Asking for pin |Pin Change|Enter your desired pin|
[INF] [00:25] [Goldwarden > Pinentry] >>> Got pin from user
/app/bin/src/gui/settings.py:253: DeprecationWarning: Gtk.Dialog.get_content_area is deprecated
  dialog.get_content_area().append(auth_preference_group)
/app/bin/src/gui/settings.py:270: DeprecationWarning: Gtk.Dialog.add_button is deprecated
  dialog.add_button("Login", Gtk.ResponseType.OK)
Gtk-Message: 00:25:10.750: GtkDialog mapped without a transient parent. This is discouraged.
[INF] [00:25] [Goldwarden > Actions] >>> Logging in with master password
[INF] [00:25] [Goldwarden > Pinentry] >>> Asking for pin |Bitwarden Password|Enter your Bitwarden password|
[INF] [00:25] [Goldwarden > Pinentry] >>> Got pin from user`

**Comment by Izaic** [comment]
Same issue here with the Flatpak GUI.

**Comment by Fxsch** [comment]
> This sounds like internal state is somehow corrupted. As you mentioned you deleted the app data, but can you still try rm -rf'ing ~/.var/app/com.quexten.Goldwarden/
, then running flatpak kill com.quexten.Goldwarden
and then restarting Goldwarden via flatpak run com.quexten.Goldwarden ?

That's how I deleted the app data. I then stopped it through GNOME's background app thingy in the control center (I assume that's doing the same thing as `flatpak kill com.quexten.Goldwarden`) and reinstalled it but, as I wrote, that didn't fix it.

> Is this a self hosted installation or official vault.bitwarden.com?

I'm not self hosting it, I'm just using vault.bitwarden.com.

Since two other people have the same issue, it seems like this isn't just an issue I'm having. Even though they already did it, I'm also going to paste the logs here, just in case. I deleted the app data and stopped the app exactly as you said this time.

---
### Log after just starting the app

```
starting goldwarden daemon /app/bin/goldwarden
[INF] [01:25] [Goldwarden > Keyring] >>> Creating new memguard keyring
[WRN] [01:25] [Goldwarden > Agent] >>> Could not read config: open /home/nicojanzen/.var/app/com.quexten.Goldwarden/config/goldwarden.json: no such file or directory
[WRN] [01:25] [Goldwarden > Agent] >>> Config is not locked. SET A PIN!!
[INF] [01:25] [Goldwarden > Agent] >>> Agent listening on /home/nicojanzen/.var/app/com.quexten.Goldwarden/data/goldwarden.sock...
[INF] [01:25] [Goldwarden > SSH] >>> SSH Agent listening on /home/nicojanzen/.var/app/com.quexten.Goldwarden/data/ssh-auth-sock
[WRN] [01:25] [Goldwarden > Agent] >>> Could not monitor idle: org.freedesktop.DBus.Error.ServiceUnknown
listening for pinentry /app/bin/goldwarden
Enabling autostart...
[INF] [01:25] [Goldwarden > Agent] >>> Received pinentry registration request
[INF] [01:25] [Goldwarden > Agent] >>> Pinentry registration success: true
autostart enabled..!?
(':1.89', '/org/freedesktop/portal/desktop/request/1_225/com/quexten/Goldwarden/18363610', 'org.freedesktop.portal.Request', 'Response', GLib.Variant('(ua{sv})', (0, {'background': <true>, 'autostart': <true>})), None)
/app/bin/src/gui/settings.py:84: DeprecationWarning: Gtk.Widget.get_style_context is deprecated
  self.autotype_button.get_style_context().add_class("suggested-action")
/app/bin/src/gui/settings.py:84: DeprecationWarning: Gtk.StyleContext.add_class is deprecated
  self.autotype_button.get_style_context().add_class("suggested-action")
/app/bin/src/gui/settings.py:44: DeprecationWarning: Adw.ActionRow.set_icon_name is deprecated
  row.set_icon_name(icon)
```

---
### Log after entering a PIN

```
[INF] [01:28] [Goldwarden > Pinentry] >>> Asking for pin |Pin Change|Enter your desired pin|
[INF] [01:28] [Goldwarden > Pinentry] >>> Got pin from user
```

---
### Log after trying to log in with password (It still showed the "Bad password" popup but it prompted me to enter the password right after that)

```
/app/bin/src/gui/settings.py:253: DeprecationWarning: Gtk.Dialog.get_content_area is deprecated
  dialog.get_content_area().append(auth_preference_group)
/app/bin/src/gui/settings.py:270: DeprecationWarning: Gtk.Dialog.add_button is deprecated
  dialog.add_button("Login", Gtk.ResponseType.OK)
Gtk-Message: 01:28:49.369: GtkDialog mapped without a transient parent. This is discouraged.
[INF] [01:28] [Goldwarden > Actions] >>> Logging in with master password
[INF] [01:28] [Goldwarden > Pinentry] >>> Asking for pin |Bitwarden Password|Enter your Bitwarden password|
[INF] [01:29] [Goldwarden > Pinentry] >>> Got pin from user
[INF] [01:29] [Goldwarden > Auth] >>> Logged in
[INF] [01:29] [Goldwarden > Keyring] >>> Unlocking keyring with account key
[INF] [01:29] [Goldwarden > Bitwarden API] >>> Performing full sync...
[INF] [01:29] [Goldwarden > Bitwarden API] >>> Sync successful, initializing keyring and vault...
[INF] [01:29] [Goldwarden > Bitwarden API] >>> Reading  0 org keys...
[INF] [01:29] [Goldwarden > Bitwarden API] >>> Initializing keyring from user symmetric key...
[INF] [01:29] [Goldwarden > Keyring] >>> Unlocking keyring with account key
[INF] [01:29] [Goldwarden > Bitwarden API] >>> Clearing vault...
[INF] [01:29] [Goldwarden > Bitwarden API] >>> Adding 158 ciphers to vault...
[INF] [01:29] [Goldwarden > Websocket] >>> Connected to websocket server...
```

---
### This showed up once in the log after clicking "ok" on the "Bad password" popup but then, as you can see, it kept showing up again (the message in the log, not the popup)

```
[WRN] [01:29] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:29] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:29] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:29] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:29] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:29] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:30] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:30] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:30] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:31] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:31] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:31] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:31] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:31] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:31] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:32] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:32] [Goldwarden > Websocket] >>> Invalid message received, length too short
[WRN] [01:32] [Goldwarden > Websocket] >>> Invalid message received, length too short
```

---
### Log after trying to log in with Client ID and Client Secret (it still showed a "Bad password" every time I clicked on "Login")

```
Traceback (most recent call last):
  File "/app/bin/src/gui/settings.py", line 187, in update_labels
    logged_in = status["loggedIn"]
                ~~~~~~^^^^^^^^^^^^
KeyError: 'loggedIn'
```

**Comment by quexten** [comment]
Thanks all for the reports!

**Comment by Qurtison** [comment]
I am also having this same issue with a fresh install of the arch package AND the flatpak

**Comment by quexten** [comment]
Should be fine on the latest main branch version, might have to make a release soon so it's fixed on stable too.

**Comment by Qurtison** [comment]
> Should be fine on the latest main branch version, might have to make a release soon so it's fixed on stable too.

I was trying to build it and see if that was the case but I was struggling to get it to work as well. I've never worked with go before. 

I was getting this error when I try to set the vault pin 

`[ERR] [10:21] [Goldwarden > IPC Messages] >>> Unregistered message type 0
Wrong response type
`

**Comment by quexten** [comment]
That sounds like the daemon is on a different version that the cli. The error message in this case in not exactly helpful, but it should be fixed by replacing your /usr/bin/goldwarden with the locally built version, then restarting the systemd daemon service.

**Comment by Qurtison** [comment]
okay I nuked everything goldwarden, restarted, and resetup 

now im getting this error lol 

Login failed: Could not sync vault: decrypt: MAC mismatch 

Just using the api client-id and secret which i copied directly from the site.. Because I got the other error you mention in the wiki

**Comment by quexten** [comment]
Seems there are some more issues to work out. 

> Login failed: Could not sync vault: decrypt: MAC mismatch

This could be a bug in Goldwarden, but it could also be a corrupted cipher in your vault. The easiest way to confirm would be to log into the web vault with your browser console open, and check if the MAC mismatch occurs there too.

The web vault currently just logs the error and skips broken ciphers. I guess we can do that too.

**Comment by LikoIlya** [comment]
> check if the MAC mismatch occurs there too

For me< the problem exists on Goldwarden (mac m1), but the web vault does not have any logged errors at browser console.

**Comment by LikoIlya** [comment]
> Because I got the other error you mention in the wiki

Same here, for the classic login (not via API keys) i got
```shell
Login failed: Could not sync vault: could not sync: Unauthorized: 
```

**Comment by erdh** [comment]
I encountered the same issue on Fedora 39 with the Flatpak variant of this app. I was using `+ addressed email` for my Bitwarden account's email address. Upon receiving this very error, I thought that this issue might be from the presence of this special character. After removing `+` from my address, I was able to log in successfully.
Hope this helps.

**Comment by quexten** [comment]
Thanks for the informative comments! I can't debug this right now due to life being ultra busy, but I will try do look at this in the coming weeks. 

The plus character is very interesting. As I recall, login requests include the email during generation of the authentication hash. I'm not sure what the official clients do, but it may be the case that they filter out such special characters in the hash.

**Comment by ImJustToNy** [comment]
I've tried to debug the issue, I don't have a plus sign in my email address, and it also doesn't work for me. However, if I log in by CLI instead of GUI, it works flawlessly. I have a lot of special characters in my password, so maybe that could help you. I think that there is some kind of problem with encoding data between GUI and CLI.

**Comment by LeMoonStar** [comment]
I am also experiencing this issue on Fedora 39 with a self-hosted Vaultwarden instance - no special characters in the email - at first in the password though, but for testing purposes I also tried a password without any special characters, which resulted in the same behaviour.

Interestingly though, the `Bad Password` pop-up shows, *BEFORE* I am even promoted for the password. I've been playing around, going trough the menus in different orders, deleting the `~/.var/app/com.quexten.Goldwarden/` directory, reinstalling - It's always the same.

The log reads:
```
flatpak run com.quexten.Goldwarden

starting goldwarden daemon /app/bin/goldwarden
[INF] [21:47] [Goldwarden > Keyring] >>> Creating new memguard keyring
[WRN] [21:47] [Goldwarden > Agent] >>> Could not read config: open /home/aaron/.var/app/com.quexten.Goldwarden/config/goldwarden.json: no such file or directory
[WRN] [21:47] [Goldwarden > Agent] >>> Config is not locked. SET A PIN!!
[INF] [21:47] [Goldwarden > Agent] >>> Agent listening on /home/aaron/.var/app/com.quexten.Goldwarden/data/goldwarden.sock...
[INF] [21:47] [Goldwarden > SSH] >>> SSH Agent listening on /home/aaron/.var/app/com.quexten.Goldwarden/data/ssh-auth-sock
[WRN] [21:47] [Goldwarden > Agent] >>> Could not monitor idle: org.freedesktop.DBus.Error.ServiceUnknown
listening for pinentry /app/bin/goldwarden
Enabling autostart...
[INF] [21:47] [Goldwarden > Agent] >>> Received pinentry registration request
[INF] [21:47] [Goldwarden > Agent] >>> Pinentry registration success: true
autostart enabled..!?
(':1.75', '/org/freedesktop/portal/desktop/request/1_687/com/quexten/Goldwarden/11719759', 'org.freedesktop.portal.Request', 'Response', GLib.Variant('(ua{sv})', (0, {'background': <true>, 'autostart': <true>})), None)
/app/bin/src/gui/settings.py:84: DeprecationWarning: Gtk.Widget.get_style_context is deprecated
  self.autotype_button.get_style_context().add_class("suggested-action")
/app/bin/src/gui/settings.py:84: DeprecationWarning: Gtk.StyleContext.add_class is deprecated
  self.autotype_button.get_style_context().add_class("suggested-action")
/app/bin/src/gui/settings.py:44: DeprecationWarning: Adw.ActionRow.set_icon_name is deprecated
  row.set_icon_name(icon)
[INF] [21:47] [Goldwarden > Pinentry] >>> Asking for pin |Pin Change|Enter your desired pin|
[INF] [21:47] [Goldwarden > Pinentry] >>> Got pin from user
/app/bin/src/gui/settings.py:253: DeprecationWarning: Gtk.Dialog.get_content_area is deprecated
  dialog.get_content_area().append(auth_preference_group)
/app/bin/src/gui/settings.py:270: DeprecationWarning: Gtk.Dialog.add_button is deprecated
  dialog.add_button("Login", Gtk.ResponseType.OK)
Gtk-Message: 21:47:36.755: GtkDialog mapped without a transient parent. This is discouraged.
[INF] [21:47] [Goldwarden > Actions] >>> Logging in with master password
[INF] [21:47] [Goldwarden > Pinentry] >>> Asking for pin |Bitwarden Password|Enter your Bitwarden password|
[INF] [21:47] [Goldwarden > Pinentry] >>> Got pin from user
Traceback (most recent call last):
  File "/app/bin/src/gui/settings.py", line 187, in update_labels
    logged_in = status["loggedIn"]
                ~~~~~~^^^^^^^^^^^^
KeyError: 'loggedIn'
```

The trace-back at the very end occurred quite a while after I stopped using the application - at least a minute later. I don't know whether it is related - The application is still running after this.

Trying to log in again, without restarting the application results in a singular additional log entry:
```
Gtk-Message: 21:55:08.834: GtkDialog mapped without a transient parent. This is discouraged.
```

No password prompt appears - just the pop-up "Bad Password".
Only after fully killing Goldwarden and starting it again, a password prompt appears at this step again.

**Comment by reitermiller** [comment]
Experiencing same behavior as LeMoonStar on Fedora 49 Workstation with a selfhosted Bitwarden instance, "Bad Password" is displayed after entering email/clientid/secret/URL but before the prompt to enter password appears, sometimes twice (first in normal GTK, then again in QT or something non-uniform)
Unlike him, I am additionally receiving a "Captcha Required" notification after the "Bad Password" error. 

Log output through Screen: 

```
eros@aardvark ~> screen -L flatpak run com.quexten.Goldwarden   
eros@aardvark ~> cat screenlog.0 
starting goldwarden daemon /app/bin/goldwarden
[INF] [11:53] [Goldwarden > Keyring] >>> Creating new memguard keyring
[INF] [11:53] [Goldwarden > Agent] >>> Agent listening on /home/eros/.var/app/com.quexten.Goldwarden/data/goldwarden.sock...
[INF] [11:53] [Goldwarden > SSH] >>> SSH Agent listening on /home/eros/.var/app/com.quexten.Goldwarden/data/ssh-auth-sock
[WRN] [11:53] [Goldwarden > Agent] >>> Could not monitor idle: org.freedesktop.DBus.Error.ServiceUnknown
listening for pinentry /app/bin/goldwarden
Enabling autostart...
[INF] [11:53] [Goldwarden > Agent] >>> Received pinentry registration request
[INF] [11:53] [Goldwarden > Agent] >>> Pinentry registration success: true
autostart enabled..!?
(':1.86', '/org/freedesktop/portal/desktop/request/1_204/com/quexten/Goldwarden/16290672', 'org.freedesktop.portal.Request', 'Response', GLib.Variant('(ua{sv})', (0, {'background': <true>, 'autostart': <true>})), None)
/app/bin/src/gui/settings.py:84: DeprecationWarning: Gtk.Widget.get_style_context is deprecated
  self.autotype_button.get_style_context().add_class("suggested-action")
/app/bin/src/gui/settings.py:84: DeprecationWarning: Gtk.StyleContext.add_class is deprecated
  self.autotype_button.get_style_context().add_class("suggested-action")
/app/bin/src/gui/settings.py:44: DeprecationWarning: Adw.ActionRow.set_icon_name is deprecated
  row.set_icon_name(icon)
[INF] [11:53] [Goldwarden > Agent] >>> Verified: true
/app/bin/src/gui/quickaccess.py:109: DeprecationWarning: Gtk.Widget.hide is deprecated
  self.results_list.hide()
/app/bin/src/gui/quickaccess.py:172: DeprecationWarning: Gtk.Widget.get_style_context is deprecated
  self.results_list.get_style_context().add_class("boxed-list")
/app/bin/src/gui/quickaccess.py:172: DeprecationWarning: Gtk.StyleContext.add_class is deprecated
  self.results_list.get_style_context().add_class("boxed-list")
[INF] [11:53] [Goldwarden > Pinentry] >>> Asking for pin |Unlock Goldwarden|Enter the vault PIN|
[INF] [11:53] [Goldwarden > Pinentry] >>> Got pin from user
[ERR] [11:53] [Goldwarden > Actions] >>> EnsureIsLoggedIn - chacha20poly1305: ciphertext too short
/app/bin/src/gui/settings.py:253: DeprecationWarning: Gtk.Dialog.get_content_area is deprecated
  dialog.get_content_area().append(auth_preference_group)
/app/bin/src/gui/settings.py:270: DeprecationWarning: Gtk.Dialog.add_button is deprecated
  dialog.add_button("Login", Gtk.ResponseType.OK)
Gtk-Message: 11:54:02.914: GtkDialog mapped without a transient parent. This is discouraged.
[INF] [11:54] [Goldwarden > Actions] >>> Logging in with master password
[INF] [11:54] [Goldwarden > Pinentry] >>> Asking for pin |Bitwarden Password|Enter your Bitwarden password|
[INF] [11:54] [Goldwarden > Pinentry] >>> Got pin from user

^CTraceback (most recent call last):
eros@aardvark ~> 
```

**Comment by zany130** [comment]
was able to get around this by
```shell
flatpak run --command=goldwarden com.quexten.Goldwarden config set-client-id YOURCLIENTID
flatpak run --command=goldwarden com.quexten.Goldwarden config set-client-secret YOURCLIENTSECRET
flatpak run --command=goldwarden com.quexten.Goldwarden vault login --email YOUREMAIL
```
for some doing this in the GUI didn't work, but after logging in through the cli everything works fine

**Comment by reitermiller** [comment]
@quexten Selfhosted instance, I have also tried to setup with keys through the Goldwarden GUI to no avail.

**Comment by quexten** [comment]
After FlatHub's build infrastructure completed building & deploying, you should be able to update to 0.2.15, alternatively:

`flatpak install --user https://dl.flathub.org/build-repo/100327/com.quexten.Goldwarden.flatpakref`

Please test if the issue persists.

**Comment by ImJustToNy** [comment]
> After FlatHub's build infrastructure completed building & deploying, you should be able to update to 0.2.15, alternatively:
> 
> `flatpak install --user https://dl.flathub.org/build-repo/100327/com.quexten.Goldwarden.flatpakref`
> 
> Please test if the issue persists.

For me, it fixed the issue, thanks!

**Comment by Damix48** [comment]
I have the same problem, but the command `flatpak install --user https://dl.flathub.org/build-repo/100327/com.quexten.Goldwarden.flatpakref` doesn't work anymore
