### ISSUE TITLE
QuickAccess window sometimes closes automatically in ~3 seconds after opening by the hotkey

### ISSUE THREAD

**Issue by MurzNN** [quexten/goldwarden#211]
Here is the video recording:

https://github.com/quexten/goldwarden/assets/336662/bc8279f6-27f5-453a-96a6-d60bab621f44

The QuickAccess window closes automatically if I don't start typing something in ~3 seconds.

**Comment by quexten** [comment]
I think we should pass errors through properly here. It closes itself if it cannot get the vault data for some reason. But to figure out why it cannot get the vault contents, the logging shouldn't be dropped.

**Comment by quexten** [comment]
Is this always or just sometimes? Also, what happens when you run `flatpak run --command=goldwarden com.quexten.Goldwarden logins list` **DO NOT POST THE OUTPUT JUST MAKE SURE THERE IS JSON FORMATTED OUTPUT** and how many entries do you approximately have (over 1k?).

**Comment by MurzNN** [comment]
With current versions it happens every time, via clicking the Quick Access button, and the same - with the hotkey. But if I quickly catch the moment of window appearing, and start typing there something, the window is not closing.

**Comment by grackeon** [comment]
Got the same issue on 0.3.2.
The `logins list` command raises a JSON error, so maybe the window closing is related to this:
```
$ flatpak run --command=goldwarden com.quexten.Goldwarden logins list
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/quexten/goldwarden/cli/client.Reader({0xa035a0, 0xc00008a138})
	/home/runner/work/goldwarden/goldwarden/cli/client/unixsocketclient.go:40 +0xe5
github.com/quexten/goldwarden/cli/client.UnixSocketConnection.ReadMessage({{0xa095a0?, 0xc00008a138?}})
	/home/runner/work/goldwarden/goldwarden/cli/client/unixsocketclient.go:92 +0x3d
github.com/quexten/goldwarden/cli/client.UnixSocketConnection.SendCommand({{0xa095a0?, 0xc00008a138?}}, {0x8bbfa0?, 0xd86de0?})
	/home/runner/work/goldwarden/goldwarden/cli/client/unixsocketclient.go:88 +0x55
github.com/quexten/goldwarden/cli/client.UnixSocketClient.SendToAgent({0x0?}, {0x8bbfa0, 0xd86de0})
	/home/runner/work/goldwarden/goldwarden/cli/client/unixsocketclient.go:52 +0xae
github.com/quexten/goldwarden/cli/cmd.ListLogins({0x0?})
	/home/runner/work/goldwarden/goldwarden/cli/cmd/logins.go:102 +0x25
github.com/quexten/goldwarden/cli/cmd.init.func17(0xc0000f7200?, {0x934f22?, 0x4?, 0x934dfa?})
	/home/runner/work/goldwarden/goldwarden/cli/cmd/logins.go:78 +0x85
github.com/spf13/cobra.(*Command).execute(0xce8c20, {0xd86de0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xce8f00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/quexten/goldwarden/cli/cmd.Execute({{0x0, 0x0}, 0x0, {0xc000032280, 0x43}, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...})
	/home/runner/work/goldwarden/goldwarden/cli/cmd/root.go:29 +0xe6
main.main()
	/home/runner/work/goldwarden/goldwarden/main.go:54 +0x618
```

**Comment by chelming** [comment]
Same issue and same error running `logins list` (#239, #98). ~900 logins.
