### ISSUE TITLE
Autotype fails

### ISSUE THREAD

**Issue by Zahrun** [quexten/goldwarden#229]
I installed goldwarden from flatpak.
I’m running Tuxedo OS 3 (based on ubuntu jammy but with KDE Plasma 6)

Autotype fails with
```
Exception in thread Thread-4 (perform_autotype):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/src/gui/quickaccess.py", line 120, in perform_autotype
    autotype.autotype(text)
  File "/app/bin/src/services/autotype/autotype.py", line 9, in autotype
    from .libportal_autotype import autotype_libportal
ImportError: cannot import name 'autotype_libportal' from 'src.services.autotype.libportal_autotype' (/app/bin/src/services/autotype/libportal_autotype.py)
```

**Comment by quexten** [comment]
Should be fixed on main

**Comment by quexten** [comment]
Please try again on `v0.3.3`

**Comment by Zahrun** [comment]
```
Exception in thread Thread-4 (perform_autotype):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/src/gui/quickaccess.py", line 119, in perform_autotype
    autotype.autotype(text)
  File "/app/bin/src/services/autotype/autotype.py", line 10, in autotype
    autotype_libportal(text)
  File "/app/bin/src/services/autotype/libportal_autotype.py", line 5, in autotype_libportal
    goldwarden.autotype(text)
    ^^^^^^^^^^
NameError: name 'goldwarden' is not defined
```

**Comment by EpicStuff** [comment]
yea, im getting the same error

**Comment by bb010g** [comment]
I can reproduce @Zahrun's error with the v0.3.3 Flatpak under Aurora running KDE Plasma.

<details><summary>Version information</summary>

```sh-session
$ flatpak info com.quexten.Goldwarden

Goldwarden - A Bitwarden compatible desktop client

          ID: com.quexten.Goldwarden
         Ref: app/com.quexten.Goldwarden/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: v0.3.3
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 11.1 MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: 1a8f7ea53dae75d092edfc78a62fb3a242e5e66077e9585e32db795d6bc14002
      Parent: b49d4270b375e72aa8e0680d654a84d14f0a2292bf5b016c90e829ea0a8640ee
     Subject: Update 3 modules (9194568a)
        Date: 2024-06-03 21:37:00 +0000

$ pkexec inxi -Sxx
System:
  Host: dell-gay15-5511 Kernel: 6.10.8-201.fsync.fc40.x86_64 arch: x86_64 bits: 64 compiler: gcc
    v: 2.41-37.fc40
  Console: pty pts/5 DM: SDDM Distro: Fedora Linux 40.20240917.0 (Kinoite)

$ rpm-ostree status --booted -v
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● ostree-image-signed:docker://ghcr.io/ublue-os/aurora-dx-nvidia:latest (index: 1)
                   Digest: sha256:48a2c2a310d768442f0861e5248048fcc508d8ccc830302d0fb80e84bed7663e
                  Version: 40.20240917.0 (2024-09-18T04:54:42Z)
               BaseCommit: 7d397e5756bcd77c36a08b3197bcdc16d6c6c0c493dcded4ad2ec255f5b648c5
                   Commit: cf36325ea74b0dcc7af45f27fabcfafaed3717407e3b8798dce3bf435aed29c0
                           ├─ copr:copr.fedorainfracloud.org:hikariknight:looking-glass-kvmfr (1970-01-01T00:00:00Z)
                           ├─ fedora (1970-01-01T00:00:00Z)
                           ├─ updates (1970-01-01T00:00:00Z)
                           └─ updates-archive (1970-01-01T00:00:00Z)
                StateRoot: default
                Initramfs: regenerate
```

</details>
