### ISSUE TITLE
Panic on `logins list`

### ISSUE THREAD

**Issue by chelming** [quexten/goldwarden#239]
I've gotten it to work once in about 10 tries.
```
flatpak run --command=goldwarden com.quexten.Goldwarden logins list
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/quexten/goldwarden/cli/client.Reader({0xa05da0, 0xc00006e140})
	/home/runner/work/goldwarden/goldwarden/cli/client/unixsocketclient.go:40 +0xe5
github.com/quexten/goldwarden/cli/client.UnixSocketConnection.ReadMessage({{0xa0bda0?, 0xc00006e140?}})
	/home/runner/work/goldwarden/goldwarden/cli/client/unixsocketclient.go:92 +0x3d
github.com/quexten/goldwarden/cli/client.UnixSocketConnection.SendCommand({{0xa0bda0?, 0xc00006e140?}}, {0x8be080?, 0xd8a080?})
	/home/runner/work/goldwarden/goldwarden/cli/client/unixsocketclient.go:88 +0x55
github.com/quexten/goldwarden/cli/client.UnixSocketClient.SendToAgent({0x0?}, {0x8be080, 0xd8a080})
	/home/runner/work/goldwarden/goldwarden/cli/client/unixsocketclient.go:52 +0xae
github.com/quexten/goldwarden/cli/cmd.ListLogins({0x0?})
	/home/runner/work/goldwarden/goldwarden/cli/cmd/logins.go:102 +0x25
github.com/quexten/goldwarden/cli/cmd.init.func17(0xc00013f300?, {0x937142?, 0x4?, 0x93701a?})
	/home/runner/work/goldwarden/goldwarden/cli/cmd/logins.go:78 +0x85
github.com/spf13/cobra.(*Command).execute(0xcebc20, {0xd8a080, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xcebf00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/quexten/goldwarden/cli/cmd.Execute({{0x0, 0x0}, 0x0, {0xc000030320, 0x46}, 0x0, 0x0, {0x0, 0x0}, {0x0, ...}, ...})
	/home/runner/work/goldwarden/goldwarden/cli/cmd/root.go:29 +0xe6
main.main()
	/home/runner/work/goldwarden/goldwarden/main.go:54 +0x618
```

```
Jun 16 15:07:14 office-pc.local systemd[2506]: Started app-flatpak-com.quexten.Goldwarden-192154.scope.
Jun 16 15:07:14 office-pc.local com.quexten.Goldwarden.desktop[4014]: [INF] [15:07] [Goldwarden > Systemauth] >>> Checking permission for unknown with session type com.quexten.goldwarden.accessvault
Jun 16 15:07:14 office-pc.local com.quexten.Goldwarden.desktop[4014]: [INF] [15:07] [Goldwarden > Systemauth] >>> Permission granted from cached session
```

**Comment by chelming** [comment]
holler with any other info I can provide. I'm running everything with the flatpak.

**Comment by Atemu** [comment]
I'm also running into this on NixOS.

What can we do to help debug this? Can I make it show the JSON input it tried to parse somehow to see if it's actually a JSON rather than e.g. an HTTP error site?
