### ISSUE TITLE
Flatpak - Panic - cipher.NewCBCDecrypter

### ISSUE THREAD

**Issue by BlueCase** [quexten/goldwarden#57]
Hi,
tried goldwarden today and get following error:
```
/app/bin/monitors/dbus_autofill_monitor.py:4: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
IS daemon running False
running daemon
Failed err None
Flatpak Config directory: /home/#MYUSER#/.var/app/com.quexten.Goldwarden/config/goldwarden.json

[INF] [14:31] [Goldwarden > Keyring] >>> Creating new memguard keyring

[INF] [14:31] [Goldwarden > Agent] >>> Agent listening on /home/#MYUSER#/.var/app/com.quexten.Goldwarden/data/goldwarden.sock...

Blocking, press ctrl+c to continue...

[INF] [14:31] [Goldwarden > SSH] >>> SSH Agent listening on /home/#MYUSER#/.var/app/com.quexten.Goldwarden/data/ssh-auth-sock

[WRN] [14:31] [Goldwarden > Agent] >>> Could not monitor idle: org.freedesktop.DBus.Error.ServiceUnknown

autostart enabled..!?
(':1.55', '/org/freedesktop/portal/desktop/request/1_2174/com/quexten/Goldwarden/10748674', 'org.freedesktop.portal.Request', 'Response', GLib.Variant('(ua{sv})', (0, {'background': <true>, 'autostart': <true>})), None)
/app/bin/settings.py:34: DeprecationWarning: Adw.ActionRow.set_icon_name is deprecated
  self.ssh_row.set_icon_name("emblem-default")
[INF] [14:31] [Goldwarden > Pinentry] >>> Asking for pin |Unlock Goldwarden|Enter the vault PIN|

[INF] [14:31] [Goldwarden > Pinentry] >>> Got pin from user

[INF] [14:31] [Goldwarden > Keyring] >>> Unlocking keyring with account key

[INF] [14:31] [Goldwarden > Auth] >>> Refreshing token

[INF] [14:31] [Goldwarden > Auth] >>> Refreshing using refresh token

[INF] [14:31] [Goldwarden > Auth] >>> Token refreshed

[INF] [14:31] [Goldwarden > Bitwarden API] >>> Performing full sync...

[INF] [14:31] [Goldwarden > Bitwarden API] >>> Sync successful, initializing keyring and vault...

[INF] [14:31] [Goldwarden > Bitwarden API] >>> Reading  1 org keys...

[INF] [14:31] [Goldwarden > Bitwarden API] >>> Initializing keyring from user symmetric key...

[INF] [14:31] [Goldwarden > Keyring] >>> Unlocking keyring with account key

[INF] [14:31] [Goldwarden > Bitwarden API] >>> Clearing vault...

[INF] [14:31] [Goldwarden > Bitwarden API] >>> Adding 282 ciphers to vault...

panic: cipher.NewCBCDecrypter: IV length must equal block size



goroutine 53 [running]:

crypto/cipher.NewCBCDecrypter({0x9f0510, 0xc0002ef8f0}, {0x0, 0x0, 0x0})

	/opt/hostedtoolcache/go/1.20.12/x64/src/crypto/cipher/cbc.go:122 +0xcc

github.com/quexten/goldwarden/agent/bitwarden/crypto.DecryptWith({0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}, ...)

	/home/runner/work/goldwarden/goldwarden/agent/bitwarden/crypto/encstring.go:159 +0x2df

github.com/quexten/goldwarden/agent/vault.(*Vault).isSSHKey(_, {0x2, 0xc0000c1130, {0x2, {0xc000366228, 0x10, 0x12}, {0xc000366240, 0x10, 0x12}, ...}, ...})

	/home/runner/work/goldwarden/goldwarden/agent/vault/vault.go:147 +0x338

github.com/quexten/goldwarden/agent/vault.(*Vault).AddOrUpdateSecureNote(_, {0x2, 0xc0000c1130, {0x2, {0xc000366228, 0x10, 0x12}, {0xc000366240, 0x10, 0x12}, ...}, ...})

	/home/runner/work/goldwarden/goldwarden/agent/vault/vault.go:82 +0x165

github.com/quexten/goldwarden/agent/bitwarden.DoFullSync({0x9f1248, 0xc0006a80f0}, 0xc0001b0230, 0xd04178?, 0xc00045bc48, 0x1)

	/home/runner/work/goldwarden/goldwarden/agent/bitwarden/sync.go:72 +0x6c5

github.com/quexten/goldwarden/agent/actions.handleUnlockVault({0xc00011a678?, {0x8?, 0xc0002b8005?, 0xa?}}, 0xc0001856c0, 0xc0001b0230, 0xc0002ba143?)

	/home/runner/work/goldwarden/goldwarden/agent/actions/vault.go:78 +0x42e

github.com/quexten/goldwarden/agent.serveAgentSession({0x9f35f0, 0xc000292018}, {0x0?, 0x0?}, 0x0?, 0x0?)

	/home/runner/work/goldwarden/goldwarden/agent/unixsocketagent.go:67 +0x252

created by github.com/quexten/goldwarden/agent.StartUnixAgent.func8

	/home/runner/work/goldwarden/goldwarden/agent/unixsocketagent.go:283 +0x55

quitting goldwarden daemon
daemon running
Exception in thread Thread-1 (unlock):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/goldwarden.py", line 83, in unlock
    raise Exception("Failed to initialize repository, err", result.stderr)
Exception: ('Failed to initialize repository, err', 'Flatpak Config directory: /home/#MYUSER#/.var/app/com.quexten.Goldwarden/config/goldwarden.json\npanic: interface conversion: interface {} is nil, not messages.IPCMessage\n\ngoroutine 1 [running]:\ngithub.com/quexten/goldwarden/client.UnixSocketClient.SendToAgent({0x0?}, {0x8ba120, 0xd04178})\n\t/home/runner/work/goldwarden/goldwarden/client/unixsocketclient.go:63 +0x269\ngithub.com/quexten/goldwarden/cmd.glob..func23(0xc95a60?, {0x92c626?, 0x0?, 0x0?})\n\t/home/runner/work/goldwarden/goldwarden/cmd/vault.go:24 +0x3a\ngithub.com/spf13/cobra.(*Command).execute(0xc95a60, {0xd04178, 0x0, 0x0})\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc93ac0)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/quexten/goldwarden/cmd.Execute({0x0, 0x0, {0x0, 0x0}, 0x0, {0xc000168140, 0x45}, 0x0, 0x0, {0x0, ...}, ...})\n\t/home/runner/work/goldwarden/goldwarden/cmd/root.go:35 +0x1fb\nmain.main()\n\t/home/runner/work/goldwarden/goldwarden/main.go:83 +0x978\n')

```

I use latest vaultwarden release as server.
OS: Manjaro Gnome

Enabled device=all for fido2 (nitrokey 3A)

**Comment by quexten** [comment]
Thank you so much for the report! Obviously, the daemon shouldn't be crashing, when something fails to decrypt. I will fix that in a bit. 

As to why it doesn't decrypt; I suspect it's either a corrupted vault entry, or the vault being in an old - unsupported - encryption format. Better logging would help here, I'll look into that.

**Comment by quexten** [comment]
The crash should be fixed now, and better logging is added, could you check the flatpak from https://github.com/quexten/goldwarden/actions/runs/7467658805 to see if that fixes it for you, and if there are logs which give a more detailed note about what's going on?

**Comment by BlueCase** [comment]
Hi,
sorry for the late reply.
Seems to be the behavior as behavior as before.

```
[INF] [11:49] [Goldwarden > Bitwarden API] >>> Initializing keyring from user symmetric key...

[INF] [11:49] [Goldwarden > Keyring] >>> Unlocking keyring with account key

[INF] [11:49] [Goldwarden > Bitwarden API] >>> Clearing vault...

[INF] [11:49] [Goldwarden > Bitwarden API] >>> Adding 282 ciphers to vault...

panic: cipher.NewCBCDecrypter: IV length must equal block size



goroutine 28 [running]:

crypto/cipher.NewCBCDecrypter({0x9e9b10, 0xc000290990}, {0x0, 0x0, 0x0})

	/opt/hostedtoolcache/go/1.20.12/x64/src/crypto/cipher/cbc.go:122 +0xcc

github.com/quexten/goldwarden/agent/bitwarden/crypto.DecryptWith({0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}, ...)

	/home/runner/work/goldwarden/goldwarden/agent/bitwarden/crypto/encstring.go:159 +0x2df

github.com/quexten/goldwarden/agent/vault.(*Vault).isSSHKey(_, {0x2, 0xc00046ac80, {0x2, {0xc0003f80c0, 0x10, 0x12}, {0xc0003f80d8, 0x10, 0x12}, ...}, ...})

	/home/runner/work/goldwarden/goldwarden/agent/vault/vault.go:147 +0x338

github.com/quexten/goldwarden/agent/vault.(*Vault).AddOrUpdateSecureNote(_, {0x2, 0xc00046ac80, {0x2, {0xc0003f80c0, 0x10, 0x12}, {0xc0003f80d8, 0x10, 0x12}, ...}, ...})

	/home/runner/work/goldwarden/goldwarden/agent/vault/vault.go:82 +0x165

github.com/quexten/goldwarden/agent/bitwarden.DoFullSync({0x9ea848, 0xc000226ed0}, 0xc0000a6280, 0xcf9738?, 0xc00051dc48, 0x1)

	/home/runner/work/goldwarden/goldwarden/agent/bitwarden/sync.go:72 +0x6c5

github.com/quexten/goldwarden/agent/actions.handleUnlockVault({0xc000229278?, {0x8?, 0xc000142005?, 0xa?}}, 0xc000198160, 0xc0000a6280, 0xc000144143?)

	/home/runner/work/goldwarden/goldwarden/agent/actions/vault.go:78 +0x42e

github.com/quexten/goldwarden/agent.serveAgentSession({0x9ecbb0, 0xc00028a018}, {0x0?, 0x0?}, 0x0?, 0x0?)

	/home/runner/work/goldwarden/goldwarden/agent/unixsocketagent.go:67 +0x252

created by github.com/quexten/goldwarden/agent.StartUnixAgent.func8

	/home/runner/work/goldwarden/goldwarden/agent/unixsocketagent.go:282 +0x55

quitting goldwarden daemon
daemon running
Exception in thread Thread-1 (unlock):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/goldwarden.py", line 83, in unlock
    raise Exception("Failed to initialize repository, err", result.stderr)
Exception: ('Failed to initialize repository, err', 'panic: interface conversion: interface {} is nil, not messages.IPCMessage\n\ngoroutine 1 [running]:\ngithub.com/quexten/goldwarden/client.UnixSocketClient.SendToAgent({}, {0x8b4b80, 0xcf9738})\n\t/home/runner/work/goldwarden/goldwarden/client/unixsocketclient.go:65 +0x29d\ngithub.com/quexten/goldwarden/cmd.glob..func20(0xc8b040?, {0x926a5f?, 0x0?, 0x0?})\n\t/home/runner/work/goldwarden/goldwarden/cmd/vault.go:24 +0x3a\ngithub.com/spf13/cobra.(*Command).execute(0xc8b040, {0xcf9738, 0x0, 0x0})\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc890a0)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/quexten/goldwarden/cmd.Execute({0x0, 0x0, {0x0, 0x0}, 0x0, {0xc00002e580, 0x31}, 0x0, 0x0, {0x0, ...}, ...})\n\t/home/runner/work/goldwarden/goldwarden/cmd/root.go:35 +0x199\nmain.main()\n\t/home/runner/work/goldwarden/goldwarden/main.go:59 +0x598\n')
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)


```

**Comment by csutcliff** [comment]
Same issue here but using from the Arch AUR rather than Flatpak. Also using vaultwarden and Argon2id (default settings) for the key.

**Comment by quexten** [comment]
Ah, sorry, the CI pipeline seemed to use an outdated daemon. Could you try once more with the flatpak from https://github.com/quexten/goldwarden/actions/runs/7579801891 ?

**Comment by BlueCase** [comment]
@quexten Seems to start now.
Here the log:
```
[INF] [19:45] [Goldwarden > Keyring] >>> Creating new memguard keyring

[INF] [19:45] [Goldwarden > Agent] >>> Agent listening on /home/bluecase/.var/app/com.quexten.Goldwarden/data/goldwarden.sock...

Blocking, press ctrl+c to continue...

[INF] [19:45] [Goldwarden > SSH] >>> SSH Agent listening on /home/bluecase/.var/app/com.quexten.Goldwarden/data/ssh-auth-sock

[WRN] [19:45] [Goldwarden > Agent] >>> Could not monitor idle: org.freedesktop.DBus.Error.ServiceUnknown

autostart enabled..!?
(':1.56', '/org/freedesktop/portal/desktop/request/1_190/com/quexten/Goldwarden/14216043', 'org.freedesktop.portal.Request', 'Response', GLib.Variant('(ua{sv})', (0, {'background': <true>, 'autostart': <true>})), None)
/app/bin/settings.py:34: DeprecationWarning: Adw.ActionRow.set_icon_name is deprecated
  self.ssh_row.set_icon_name("emblem-default")
[INF] [19:45] [Goldwarden > Pinentry] >>> Asking for pin |Unlock Goldwarden|Enter the vault PIN|

[INF] [19:45] [Goldwarden > Pinentry] >>> Got pin from user

[INF] [19:45] [Goldwarden > Keyring] >>> Unlocking keyring with account key

[INF] [19:45] [Goldwarden > Actions] >>> Unlocking vault...

[INF] [19:45] [Goldwarden > Auth] >>> Refreshing token

[INF] [19:45] [Goldwarden > Auth] >>> Refreshing using refresh token

[INF] [19:45] [Goldwarden > Auth] >>> Token refreshed

[INF] [19:45] [Goldwarden > Actions] >>> Token refreshed

[INF] [19:45] [Goldwarden > Bitwarden API] >>> Performing full sync...

[INF] [19:45] [Goldwarden > Bitwarden API] >>> Sync successful, initializing keyring and vault...

[INF] [19:45] [Goldwarden > Bitwarden API] >>> Reading  1 org keys...

[INF] [19:45] [Goldwarden > Bitwarden API] >>> Initializing keyring from user symmetric key...

[INF] [19:45] [Goldwarden > Keyring] >>> Unlocking keyring with account key

[INF] [19:45] [Goldwarden > Bitwarden API] >>> Clearing vault...

[INF] [19:45] [Goldwarden > Bitwarden API] >>> Adding 281 ciphers to vault...

[ERR] [19:45] [Goldwarden > Vault] >>> Failed to decrypt field name with on cipher 37cecb6b-6d93-4efb-aabf-7f65df6d0864%!(EXTRA string=decrypt: cipher of unsupported type '\x00')

[INF] [19:45] [Goldwarden > Websocket] >>> Connected to websocket server...

```
