### ISSUE TITLE
CLI commands when using flatpak?

### ISSUE THREAD

**Issue by MostHated** [quexten/goldwarden#89]
Hey there,
I installed the flatpak version and everything is showing as setup properly, ex: says logged in, hotkey works to bring up authentication and the goldwarden search comes up, but it is empty. I see that the 'last sync' is set to 'never', etc. Most of the wiki seems to assume you have the binary installed for commands like `goldwarden vault ... etc`, but when using the flatpak, it is not available. Is there a specific alias to create or something which would give CLI access in order to be able to run all the additional commands, or is the flatpak install supposed to provide UI functionality in addition to having the CLI binary installed at the same time?

Thanks,
-MH

**Comment by MostHated** [comment]
(My apologies, I forgot to mention just in case it is needed for any context, I am self-hosting via VaultWarden)

Interesting, that did make it sync now. I installed this the other day, and have restarted my PC twice since then. I had used the hotkey a time or two to test it out both before and after at least one of the restarts, but this seems to be the first time it actually did sync. 
This is what the log looked like. It looks like I need to setup the websocket. I did use the hotkey just now, and items did show up when I started typing, so it looks like all should be well going forward at least.

```log
zsh ❯ flatpak kill com.quexten.Goldwarden

~
zsh ❯ flatpak run com.quexten.Goldwarden
/app/bin/monitors/dbus_autofill_monitor.py:4: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
IS daemon running False
running daemon
Failed err None
Flatpak Config directory: /home/mosthated/.var/app/com.quexten.Goldwarden/config/goldwarden.json

[INF] [17:20] [Goldwarden > Keyring] >>> Creating new memguard keyring
[INF] [17:20] [Goldwarden > Agent] >>> Agent listening on /home/mosthated/.var/app/com.quexten.Goldwarden/data/goldwarden.sock...

Blocking, press ctrl+c to continue...

[INF] [17:20] [Goldwarden > SSH] >>> SSH Agent listening on /home/mosthated/.var/app/com.quexten.Goldwarden/data/ssh-auth-sock

autostart enabled..!?
(':1.89', '/org/freedesktop/portal/desktop/request/1_709/com/quexten/Goldwarden/17013319', 'org.freedesktop.portal.Request', 'Response', GLib.Variant('(ua{sv})', (0, {'background': <true>, 'autostart': <true>})), None)
/app/bin/settings.py:49: DeprecationWarning: Adw.ActionRow.set_icon_name is deprecated
  self.ssh_row.set_icon_name("emblem-default")

[INF] [17:20] [Goldwarden > Pinentry] >>> Asking for pin |Unlock Goldwarden|Enter the vault PIN|
[INF] [17:20] [Goldwarden > Pinentry] >>> Got pin from user
[INF] [17:20] [Goldwarden > Keyring] >>> Unlocking keyring with account key
[INF] [17:20] [Goldwarden > Actions] >>> Unlocking vault...
[INF] [17:20] [Goldwarden > Auth] >>> Refreshing token
[INF] [17:20] [Goldwarden > Auth] >>> Refreshing using API Key
[INF] [17:20] [Goldwarden > Auth] >>> Token refreshed
[INF] [17:20] [Goldwarden > Actions] >>> Token refreshed
[INF] [17:20] [Goldwarden > Bitwarden API] >>> Performing full sync...
[INF] [17:20] [Goldwarden > Bitwarden API] >>> Sync successful, initializing keyring and vault...
[INF] [17:20] [Goldwarden > Bitwarden API] >>> Reading  1 org keys...
[INF] [17:20] [Goldwarden > Bitwarden API] >>> Initializing keyring from user symmetric key...
[INF] [17:20] [Goldwarden > Keyring] >>> Unlocking keyring with account key
[INF] [17:20] [Goldwarden > Bitwarden API] >>> Clearing vault...
[INF] [17:20] [Goldwarden > Bitwarden API] >>> Adding 1570 ciphers to vault...
[ERR] [17:20] [Goldwarden > Websocket] >>> Websocket error websocket: bad handshake
[ERR] [17:21] [Goldwarden > Websocket] >>> Websocket error websocket: bad handshake
[ERR] [17:23] [Goldwarden > Websocket] >>> Websocket error websocket: bad handshake
[ERR] [17:24] [Goldwarden > Websocket] >>> Websocket error websocket: bad handshake
```

**Comment by MostHated** [comment]
Interestingly, when I installed the CLI along side the flatpak, the flatpaks UI is showing everything as being the same as it was before installing the cli, the UI no longer shows results when trying to search. Though, it looks like I figured out what that issue was just now. When I installed the cli, I went to open the config file and formatted the json so I could better see what it contained (to see if I needed to set the socket path to use in there, but I set it via env variable after reading more through the wiki), and had saved it, which it looks like it doesn't like. It gave an error when trying to read it.

```sh

Traceback (most recent call last):
  File "/app/bin/autofill.py", line 23, in on_activate
    logins = goldwarden.get_vault_logins()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/goldwarden.py", line 112, in get_vault_logins
    raise Exception("Failed to initialize repository, err", result.stderr)
Exception: ('Failed to initialize repository, err', 'Flatpak Config directory: /home/mosthated/.var/app/com.quexten.Goldwarden/config/goldwarden.json\npanic: unexpected end of JSON input\n\ngoroutine 1 [running]:\ngithub.com/quexten/goldwarden/client.reader({0x9ef260, 0xc0000141a0})\n\t/home/runner/work/goldwarden/goldwarden/client/unixsocketclient.go:36 +0xe6\ngithub.com/quexten/goldwarden/client.UnixSocketClient.SendToAgent({0x0?}, {0x8bb100, 0xd06198})\n\t/home/runner/work/goldwarden/goldwarden/client/unixsocketclient.go:62 +0x1f1\ngithub.com/quexten/goldwarden/cmd.ListLogins({0x9efb80?, 0xc0001b62a0?})\n\t/home/runner/work/goldwarden/goldwarden/cmd/logins.go:100 +0x39\ngithub.com/quexten/goldwarden/cmd.glob..func12(0xc957e0?, {0x92d806?, 0x0?, 0x0?})\n\t/home/runner/work/goldwarden/goldwarden/cmd/logins.go:69 +0x45\ngithub.com/spf13/cobra.(*Command).execute(0xc957e0, {0xd06198, 0x0, 0x0})\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc95ac0)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/quexten/goldwarden/cmd.Execute({0x0, 0x0, {0x0, 0x0}, 0x0, {0xc000030460, 0x46}, 0x0, 0x0, {0x0, ...}, ...})\n\t/home/runner/work/goldwarden/goldwarden/cmd/root.go:35 +0x1fb\nmain.main()\n\t/home/runner/work/goldwarden/goldwarden/main.go:83 +0x965\n')
/app/bin/autofill.py:46: DeprecationWarning: Gtk.Widget.show is deprecated
  self.history_list.show()

```
I reverted and made the config a single line, and now searching works again.

**Comment by quexten** [comment]
You can run the cli in the flatpak with `flatpak run --command=goldwarden com.quexten.Goldwarden`. (You can also alias this in your shell to make it less cumbersome).

**Comment by quexten** [comment]
(I think this solves the issue. I'll add it to the wiki. If not feel free to re-open)
