### ISSUE TITLE
Panic on `logins list`

### ISSUE THREAD

**Issue by benni347** [quexten/goldwarden#98]
Hey, when running `goldwarden logins list`, I get a panic at the bottom you will se the error.
Versions:
 - goldwarden: 0.2.10-1 from the aur
 - Vaultwarden: 2024.1.2

The vault is unlocked and readable since I can use the ssh integration:
```json
{
  "locked": false ,
  "loginEntries": 1288 ,
  "noteEntries": 47 ,
  "lastSynced":	"2024-02-05 11:09:03 +0100 CET",
  "websocketConnected": true ,
  "pinSet": true ,
  "loggedIn": true
}
```

Error:
```
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/quexten/goldwarden/client.reader({0x62bb569259b8, 0xc000060140})
	github.com/quexten/goldwarden/client/unixsocketclient.go:36 +0xe5
github.com/quexten/goldwarden/client.UnixSocketClient.SendToAgent({0x0?}, {0x62bb568abde0, 0x62bb56c4ac60})
	github.com/quexten/goldwarden/client/unixsocketclient.go:62 +0x1d3
github.com/quexten/goldwarden/cmd.ListLogins({0x62bb56925298?, 0xc0000ba2a0?})
	github.com/quexten/goldwarden/cmd/logins.go:100 +0x33
github.com/quexten/goldwarden/cmd.glob..func12(0xc0000d1200?, {0x62bb5677d452?, 0x4?, 0x62bb5677d34e?})
	github.com/quexten/goldwarden/cmd/logins.go:69 +0x38
github.com/spf13/cobra.(*Command).execute(0x62bb56bdfa40, {0x62bb56c4ac60, 0x0, 0x0})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0x62bb56bdfd20)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/quexten/goldwarden/cmd.Execute({0x0, 0x0, {0x0, 0x0}, 0x0, {0xc00002aae0, 0x2d}, 0x0, 0x0, {0x0, ...}, ...})
	github.com/quexten/goldwarden/cmd/root.go:35 +0x1ee
main.main()
	github.com/quexten/goldwarden/main.go:83 +0x938
```

**Comment by quexten** [comment]
Hm, in this case the error message doesn't help much because the client also crashes due to malformed input. The actual error is probably logged in the daemons logs, do you happen to still have those? (`journalctl --user -u goldwarden`)

**Comment by benni347** [comment]
Yes but I do not think they are very helpful.

```
Feb 09 21:57:07 archlinux goldwarden[9943]: [INF] [21:57] [Goldwarden > Systemauth] >>> Checking permission for goldwarden with session type com.quexten.goldwarden.accessvault
Feb 09 21:57:07 archlinux goldwarden[9943]: [INF] [21:57] [Goldwarden > Systemauth] >>> Permission granted from cached session
Feb 09 21:57:07 archlinux goldwarden[9943]: [INF] [21:57] [Goldwarden > Pinentry] >>> Asking for approval |Approve List Credentials|cdrc on kitty>fish>goldwarden is trying access all credentials|
Feb 09 21:57:08 archlinux goldwarden[9943]: [INF] [21:57] [Goldwarden > Pinentry] >>> Got approval from user
```

**Comment by quexten** [comment]
Might be fixed on latest master. The buffer size for the result was limited to 1MiB. I increased it to 4MiB for now. I guess long term this should be dynamically allocated.

**Comment by quexten** [comment]
When you have time, feel free to try on v0.2.12
